from custom.page_controller_abc import PageController
from controllers.recipes_controller import RecipesController
from controllers.editation_controller import EditationController
from controllers.addition_controller import AdditionController
from controllers.detail_controller import DetailController