from views.main_view import MainView
from controllers.page_controller_abc import PageController
from controllers.home_controller import HomeController
from controllers.editation_controller import EditationController
from controllers.addition_controller import AdditionController