from pages.add_recipe_page import AddRecipePage
from pages.edit_recipe_page import EditRecipePage
from pages.recipes_page import RecipesPage
from pages.detail_recipe_page import DetailRecipePage
from pages.ingredients_page import IngredientsPage
from pages.add_ingredient_page import AddIngredientPage